# Generated by Django 4.2.18 on 2025-02-05 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_alter_coursemodel_instructor_alter_coursemodel_title"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dashusermodel",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="dashusermodel",
            name="user_permissions",
        ),
        migrations.RemoveField(
            model_name="dashuserpermissions",
            name="permission",
        ),
        migrations.RemoveField(
            model_name="dashuserpermissions",
            name="user",
        ),
        migrations.DeleteModel(
            name="DashUserGroups",
        ),
        migrations.DeleteModel(
            name="DashUserModel",
        ),
        migrations.DeleteModel(
            name="DashUserPermissions",
        ),
    ]
